services:
  # Services with Dockerfiles
  # Backend Service
  backend:
    build: ./Backend
    container_name: clubiq_backend
    restart: unless-stopped
    env_file:
      - Backend/.env
    depends_on:
      - postgres
    volumes:
      - ./Backend:/app
    command: flask run --host=0.0.0.0 --port=5000
    networks:
      - internal

  # Frontend Service
  frontend:
    build: ./Frontend
    container_name: clubiq_frontend
    restart: unless-stopped
    depends_on:
      - backend
    env_file:
      - Frontend/.env
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    networks:
      - internal

  # Services with only images
  # Database
  postgres:
    image: postgres:16
    container_name: clubiq_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal

  # Database Web GUI
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      SCRIPT_NAME: /pgadmin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - internal

  # Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - internal
    depends_on:
      - frontend
      - backend
      - postgres
      - pgadmin

# Persistent Storage
volumes:
  postgres_data:
  pgadmin_data:

# Internal Docker Network
networks:
  internal:
    driver: bridge
